spring:
    application:
        name: jenkins-integration
management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"
    server:
        port: 8081